server:
  port: 8022
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ramin2004
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  liquibase:
    change-log: liquibase/changelog-master.yml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher



